import {TONE, SEMITONE} from './intervals';

const CHROMATIC_SCALE = [SEMITONE, SEMITONE, SEMITONE, SEMITONE, SEMITONE,
	SEMITONE, SEMITONE, SEMITONE, SEMITONE, SEMITONE, SEMITONE, SEMITONE];
const WHOLE_TONE_SCALE = [TONE, TONE, TONE, TONE, TONE, TONE, TONE];

const IONIAN_MODE = [TONE, TONE, SEMITONE, TONE, TONE, TONE, SEMITONE];
const DORIAN_MODE = [TONE, SEMITONE, TONE, TONE, TONE, SEMITONE, TONE];
const PHRYGIAN_MODE = [SEMITONE, TONE, TONE, TONE, SEMITONE, TONE, TONE];
const LYDIAN_MODE = [TONE, TONE, TONE, SEMITONE, TONE, TONE, SEMITONE];
const MIXOLYDIAN_MODE = [TONE, TONE, SEMITONE, TONE, TONE, SEMITONE, TONE];
const AEOLIAN_MODE = [TONE, SEMITONE, TONE, TONE, SEMITONE, TONE, TONE];
const LOCRIAN_MODE = [SEMITONE, TONE, TONE, SEMITONE, TONE, TONE, TONE];

const MAJOR_SCALE = IONIAN_MODE;
const MINOR_SCALE = AEOLIAN_MODE;
