import {TONE, SEMITONE} from './intervals';

export const CHROMATIC_SCALE = [SEMITONE, SEMITONE, SEMITONE, SEMITONE, SEMITONE,
	SEMITONE, SEMITONE, SEMITONE, SEMITONE, SEMITONE, SEMITONE, SEMITONE];
export const WHOLE_TONE_SCALE = [TONE, TONE, TONE, TONE, TONE, TONE, TONE];

export const IONIAN_MODE = [TONE, TONE, SEMITONE, TONE, TONE, TONE, SEMITONE];
export const DORIAN_MODE = [TONE, SEMITONE, TONE, TONE, TONE, SEMITONE, TONE];
export const PHRYGIAN_MODE = [SEMITONE, TONE, TONE, TONE, SEMITONE, TONE, TONE];
export const LYDIAN_MODE = [TONE, TONE, TONE, SEMITONE, TONE, TONE, SEMITONE];
export const MIXOLYDIAN_MODE = [TONE, TONE, SEMITONE, TONE, TONE, SEMITONE,
	TONE];
export const AEOLIAN_MODE = [TONE, SEMITONE, TONE, TONE, SEMITONE, TONE, TONE];
export const LOCRIAN_MODE = [SEMITONE, TONE, TONE, SEMITONE, TONE, TONE, TONE];

export const MAJOR_SCALE = IONIAN_MODE;
export const MINOR_SCALE = AEOLIAN_MODE;
