import {PERFECT_UNISON, MAJOR_THIRD, PERFECT_FIFTH, MINOR_THIRD,
	AUGMENTED_FIFTH, DIMINISHED_FIFTH, PERFECT_OCTAVE} from './intervals';

export const MAJOR_TRIAD = [PERFECT_UNISON, MAJOR_THIRD, PERFECT_FIFTH];
export const MINOR_TRIAD = [PERFECT_UNISON, MINOR_THIRD, PERFECT_FIFTH];
export const AUGMENTED_TRIAD = [PERFECT_UNISON, MAJOR_THIRD,AUGMENTED_FIFTH];
export const DIMINISHED_TRIAD = [PERFECT_UNISON, MINOR_THIRD, DIMINISHED_FIFTH];

export const ROOT_POSITION = [PERFECT_UNISON, PERFECT_UNISON, PERFECT_UNISON];
export const FIRST_INVERSION = [PERFECT_OCTAVE, PERFECT_UNISON, PERFECT_UNISON];
export const SECOND_INVERSION = [PERFECT_OCTAVE, PERFECT_OCTAVE,
	PERFECT_UNISON];
